CREATE DATABASE livraria;

CREATE TABLE livro (
  `id` INT NOT NULL AUTO_INCREMENT,
  `isbn` VARCHAR(17) NOT NULL,
  `titulo` VARCHAR(20) NOT NULL,
  `autor` VARCHAR(20) NOT NULL,
  `editora` VARCHAR(20) NOT NULL,
  `data_cadastro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `data_atualizacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_livro PRIMARY KEY(id)
);
